import { z } from "zod";
import dotenv from "dotenv";

dotenv.config();

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  PORT: z.string().default("4000"),
  DATABASE_URL: z.string().min(1, "DATABASE_URL is required"),
  RPC_URL: z.string().min(1, "RPC_URL is required"),
  WDK_API_KEY: z.string().min(1, "WDK_API_KEY is required"),
  WDK_TRANSFER_MAX_FEE: z.string().default("1000000000000000"),
  WDK_INDEXER_BASE_URL: z.string().default("https://wdk-api.tether.io"),
  WDK_INDEXER_API_KEY: z.string().optional(),
  MASTER_KEY: z.string().min(32, "MASTER_KEY must be at least 32 chars"),
  ADMIN_SEED_PAYLOAD: z.string().min(10, "ADMIN_SEED_PAYLOAD is required"),
  DEFAULT_CHAIN: z.string().default("ethereum"),
  TREASURY_TOKEN_SYMBOL: z.string().optional(),
  TREASURY_TOKEN_ADDRESS: z.string().optional(),
  TREASURY_TOKEN_DECIMALS: z.string().default("18"),
  TREASURY_TOKEN_BLOCKCHAIN: z.string().default("ethereum"),
  TON_RPC_URL: z.string().optional(),
  TRON_RPC_URL: z.string().optional(),
  BTC_RPC_URL: z.string().optional(),
  SOLANA_RPC_URL: z.string().optional(),
  LLM_PROVIDER: z.enum(["openai", "anthropic", "gemini"]).default("openai"),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_MODEL: z.string().default("gpt-4o-mini"),
  ANTHROPIC_API_KEY: z.string().optional(),
  ANTHROPIC_MODEL: z.string().default("claude-sonnet-4-20250514"),
  GEMINI_API_KEY: z.string().optional(),
  GEMINI_MODEL: z.string().default("gemini-1.5-pro"),
  PAYROLL_CRON: z.string().default("0 9 1 * *"),
  INVESTMENT_CRON: z.string().default("0 */6 * * *"),
  REPORT_CRON: z.string().default("0 9 * * 1"),
  MAX_TX_AMOUNT: z.string().default("100000"),
  TREASURY_PAYROLL_RESERVE_PCT: z.string().default("0.6"),
  TREASURY_LENDING_PCT: z.string().default("0.2"),
  TREASURY_INVESTMENT_PCT: z.string().default("0.2"),
  PRICE_API_URL: z.string().optional(),
  PRICE_API_KEY: z.string().optional(),
  CMC_API_KEY: z.string().optional(),
  CMC_API_URL: z.string().optional(),
  CMC_LISTINGS_URL: z.string().optional(),
  INVESTMENT_WALLET_ADDRESS: z.string().optional(),
  EMAIL_PROVIDER_MODE: z.string().optional(),
  CLAWGENCY_PLATFORM_EMAIL: z.string().optional(),
  GMAIL_ACCESS_TOKEN: z.string().optional(),
  GMAIL_REPLY_LABEL: z.string().optional(),
  GOOGLE_OAUTH_CLIENT_ID: z.string().optional(),
  GOOGLE_OAUTH_CLIENT_SECRET: z.string().optional(),
  GMAIL_OAUTH_REDIRECT_URI: z.string().optional(),
  GMAIL_REFRESH_TOKEN_FILE: z.string().optional(),
  GMAIL_REFRESH_TOKEN: z.string().optional(),
  GMAIL_CLIENT_ID: z.string().optional(),
  GMAIL_CLIENT_SECRET: z.string().optional(),
  GMAIL_REDIRECT_URI: z.string().optional(),
  GMAIL_SENDER_EMAIL: z.string().optional(),
  EMAIL_FROM: z.string().optional(),
  ADMIN_EMAILS: z.string().optional(),
  HUMAN_TASKS_PROVIDER: z.enum(["local", "openclaw"]).default("local"),
  APP_BASE_URL: z.string().default("http://localhost:3000"),
  VAULT_CONTRACT_ADDRESS: z.string().min(1, "VAULT_CONTRACT_ADDRESS is required"),
  LOAN_CONTRACT_ADDRESS: z.string().min(1, "LOAN_CONTRACT_ADDRESS is required"),
  ORCHESTRATOR_INTERVAL_MS: z.string().default("120000"),
  INVESTMENT_CONTRACT_ADDRESS: z.string().optional(),
  AAVE_POOL_ADDRESS: z.string().default("0x6Ae43d3271ff6888e7Fc43Fd7321a503ff738951"),
  AAVE_WETH_GATEWAY: z.string().default("0xD322A49006FC828F9B5B37Ab215F99B4E5caB19C"),
  AAVE_SUPPLY_TOKEN_ADDRESS: z.string().optional(),
  AAVE_SUPPLY_TOKEN_DECIMALS: z.string().default("18"),
  AAVE_ATOKEN_ADDRESS: z.string().optional(),
  AAVE_ATOKEN_DECIMALS: z.string().default("18"),
  WETH_ADDRESS: z.string().optional(),
  AAVE_WRAP_NATIVE: z.string().default("true"),
  AAVE_UNWRAP_NATIVE: z.string().default("true"),
  MAX_AAVE_EXPOSURE_PCT: z.string().default("0.30"),
  LOAN_AUTO_APPROVAL_THRESHOLD: z.string().default("0.02")
});

export const env = envSchema.parse(process.env);
